modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="words_of_radiance"
version="1.0.0"
displayName="Words of Radiance"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Jon, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.words_of_radiance]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.123,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.words_of_radiance]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration