
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.wordsofradiance.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.wordsofradiance.item.inventory.RestoreOrderCrusadeBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.HuntCrusadeBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.DefendInnocentCrusadeBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.DedicationOccupationBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.DedicationLandBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.DedicationConquestBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.DedicationBeyondDeathBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.CrusadeTyrantBookInventoryCapability;
import net.mcreator.wordsofradiance.item.inventory.CrusadeMonstrosityBookInventoryCapability;
import net.mcreator.wordsofradiance.item.WindrunnerShardplateItem;
import net.mcreator.wordsofradiance.item.WindrunnerBladeItem;
import net.mcreator.wordsofradiance.item.WillshaperPlateItem;
import net.mcreator.wordsofradiance.item.WillshaperBladeItem;
import net.mcreator.wordsofradiance.item.VedelsBladeItem;
import net.mcreator.wordsofradiance.item.VedelsBladeBondedItem;
import net.mcreator.wordsofradiance.item.TruthwatcherPlateItem;
import net.mcreator.wordsofradiance.item.TruthwatcherBladeItem;
import net.mcreator.wordsofradiance.item.TensionWoodenSwordItem;
import net.mcreator.wordsofradiance.item.TensionWoodenShovelItem;
import net.mcreator.wordsofradiance.item.TensionWoodenPickItem;
import net.mcreator.wordsofradiance.item.TensionWoodenHoeItem;
import net.mcreator.wordsofradiance.item.TensionWoodenAxeItem;
import net.mcreator.wordsofradiance.item.TensionStoneSwordItem;
import net.mcreator.wordsofradiance.item.TensionStoneShovelItem;
import net.mcreator.wordsofradiance.item.TensionStonePickItem;
import net.mcreator.wordsofradiance.item.TensionStoneHoeItem;
import net.mcreator.wordsofradiance.item.TensionStoneAxeItem;
import net.mcreator.wordsofradiance.item.TensionIronSwordItem;
import net.mcreator.wordsofradiance.item.TensionIronShovelItem;
import net.mcreator.wordsofradiance.item.TensionIronPickItem;
import net.mcreator.wordsofradiance.item.TensionIronHoeItem;
import net.mcreator.wordsofradiance.item.TensionIronAxeItem;
import net.mcreator.wordsofradiance.item.TensionInfusedIronArmorItem;
import net.mcreator.wordsofradiance.item.TensionInfusedGoldArmorItem;
import net.mcreator.wordsofradiance.item.TensionInfusedDiamondArmorItem;
import net.mcreator.wordsofradiance.item.TensionInfusedChainmailArmorItem;
import net.mcreator.wordsofradiance.item.TensionGoldSwordItem;
import net.mcreator.wordsofradiance.item.TensionGoldShovelItem;
import net.mcreator.wordsofradiance.item.TensionGoldPickItem;
import net.mcreator.wordsofradiance.item.TensionGoldHoeItem;
import net.mcreator.wordsofradiance.item.TensionGoldAxeItem;
import net.mcreator.wordsofradiance.item.TensionDiamondSwordItem;
import net.mcreator.wordsofradiance.item.TensionDiamondShovelItem;
import net.mcreator.wordsofradiance.item.TensionDiamondPickItem;
import net.mcreator.wordsofradiance.item.TensionDiamondHoeItem;
import net.mcreator.wordsofradiance.item.TensionDiamondAxeItem;
import net.mcreator.wordsofradiance.item.TalnsBladeItem;
import net.mcreator.wordsofradiance.item.TalnsBladeBondedItem;
import net.mcreator.wordsofradiance.item.StonewardPlateItem;
import net.mcreator.wordsofradiance.item.StonewardBladeItem;
import net.mcreator.wordsofradiance.item.SkybreakerPlateItem;
import net.mcreator.wordsofradiance.item.SkybreakerBladeItem;
import net.mcreator.wordsofradiance.item.RestoreOrderCrusadeBookItem;
import net.mcreator.wordsofradiance.item.PrallasBladeItem;
import net.mcreator.wordsofradiance.item.PrallasBladeBondedItem;
import net.mcreator.wordsofradiance.item.NalesBladeItem;
import net.mcreator.wordsofradiance.item.NalesBladeBondedItem;
import net.mcreator.wordsofradiance.item.LightweaverPlateItem;
import net.mcreator.wordsofradiance.item.LightweaverBladeItem;
import net.mcreator.wordsofradiance.item.KalaksBladeItem;
import net.mcreator.wordsofradiance.item.KalaksBladeBondedItem;
import net.mcreator.wordsofradiance.item.JezriensBladeItem;
import net.mcreator.wordsofradiance.item.JezriensBladeBondedItem;
import net.mcreator.wordsofradiance.item.HuntCrusadeBookItem;
import net.mcreator.wordsofradiance.item.ElsecallerPlateItem;
import net.mcreator.wordsofradiance.item.ElsecallerBladeItem;
import net.mcreator.wordsofradiance.item.EdgedancerPlateItem;
import net.mcreator.wordsofradiance.item.EdgedancerBladeItem;
import net.mcreator.wordsofradiance.item.DustbringerPlateItem;
import net.mcreator.wordsofradiance.item.DustbringerBladeItem;
import net.mcreator.wordsofradiance.item.DefendInnocentCrusadeBookItem;
import net.mcreator.wordsofradiance.item.DedicationOccupationBookItem;
import net.mcreator.wordsofradiance.item.DedicationLandBookItem;
import net.mcreator.wordsofradiance.item.DedicationConquestBookItem;
import net.mcreator.wordsofradiance.item.DedicationBeyondDeathBookItem;
import net.mcreator.wordsofradiance.item.DeadZirconBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadZirconBladeItem;
import net.mcreator.wordsofradiance.item.DeadWhiteBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadWhiteBladeItem;
import net.mcreator.wordsofradiance.item.DeadStonewardBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadRedBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadRedBladeItem;
import net.mcreator.wordsofradiance.item.DeadPurpleBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadPurpleBladeItem;
import net.mcreator.wordsofradiance.item.DeadPinkRedBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadPinkRedBladeItem;
import net.mcreator.wordsofradiance.item.DeadOrangeBladeItem;
import net.mcreator.wordsofradiance.item.DeadGreenBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadGreenBladeItem;
import net.mcreator.wordsofradiance.item.DeadBlueBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadBlueBladeItem;
import net.mcreator.wordsofradiance.item.DeadBlackBladeWithGemItem;
import net.mcreator.wordsofradiance.item.DeadBlackBladeItem;
import net.mcreator.wordsofradiance.item.CrusadeTyrantBookItem;
import net.mcreator.wordsofradiance.item.CrusadeMonstrosityBookItem;
import net.mcreator.wordsofradiance.item.ChannahsBladeItem;
import net.mcreator.wordsofradiance.item.ChannahsBladeBondedItem;
import net.mcreator.wordsofradiance.item.BondedDeadBlueBladeItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladeZirconItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladeWhiteItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladeRedItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladePurpleItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladePinkRedItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladeOrangeItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladeGreenItem;
import net.mcreator.wordsofradiance.item.BondedDeadBladeBlackItem;
import net.mcreator.wordsofradiance.item.BeadsItem;
import net.mcreator.wordsofradiance.item.BattarsBladeItem;
import net.mcreator.wordsofradiance.item.BattarsBladeBondedItem;
import net.mcreator.wordsofradiance.item.AshsBladeItem;
import net.mcreator.wordsofradiance.item.AshsBladeBondedItem;
import net.mcreator.wordsofradiance.WordsOfRadianceMod;

import java.util.function.Function;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class WordsOfRadianceModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(WordsOfRadianceMod.MODID);
	public static final DeferredItem<Item> DEDICATION_LAND_BOOK = register("dedication_land_book", DedicationLandBookItem::new);
	public static final DeferredItem<Item> DEDICATION_CONQUEST_BOOK = register("dedication_conquest_book", DedicationConquestBookItem::new);
	public static final DeferredItem<Item> DEDICATION_OCCUPATION_BOOK = register("dedication_occupation_book", DedicationOccupationBookItem::new);
	public static final DeferredItem<Item> DEDICATION_BEYOND_DEATH_BOOK = register("dedication_beyond_death_book", DedicationBeyondDeathBookItem::new);
	public static final DeferredItem<Item> CRUSADE_TYRANT_BOOK = register("crusade_tyrant_book", CrusadeTyrantBookItem::new);
	public static final DeferredItem<Item> CRUSADE_MONSTROSITY_BOOK = register("crusade_monstrosity_book", CrusadeMonstrosityBookItem::new);
	public static final DeferredItem<Item> DEFEND_INNOCENT_CRUSADE_BOOK = register("defend_innocent_crusade_book", DefendInnocentCrusadeBookItem::new);
	public static final DeferredItem<Item> RESTORE_ORDER_CRUSADE_BOOK = register("restore_order_crusade_book", RestoreOrderCrusadeBookItem::new);
	public static final DeferredItem<Item> HUNT_CRUSADE_BOOK = register("hunt_crusade_book", HuntCrusadeBookItem::new);
	public static final DeferredItem<Item> ILLUSION_STONE = block(WordsOfRadianceModBlocks.ILLUSION_STONE);
	public static final DeferredItem<Item> ILLUSION_DIRT = block(WordsOfRadianceModBlocks.ILLUSION_DIRT);
	public static final DeferredItem<Item> ILLUSION_OAK_PLANK = block(WordsOfRadianceModBlocks.ILLUSION_OAK_PLANK);
	public static final DeferredItem<Item> ILLUSION_PLAYER_SPAWN_EGG = register("illusion_player_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.ILLUSION_PLAYER.get(), properties));
	public static final DeferredItem<Item> ILLUSION_BIRCH_PLANK = block(WordsOfRadianceModBlocks.ILLUSION_BIRCH_PLANK);
	public static final DeferredItem<Item> ILLUSION_DARK_OAK_PLANK = block(WordsOfRadianceModBlocks.ILLUSION_DARK_OAK_PLANK);
	public static final DeferredItem<Item> ILLUSION_SPRUCE_PLANK = block(WordsOfRadianceModBlocks.ILLUSION_SPRUCE_PLANK);
	public static final DeferredItem<Item> ILLUSION_OAK_LOG = block(WordsOfRadianceModBlocks.ILLUSION_OAK_LOG);
	public static final DeferredItem<Item> ILLUSION_BIRCH_LOG = block(WordsOfRadianceModBlocks.ILLUSION_BIRCH_LOG);
	public static final DeferredItem<Item> ILLUSION_DARK_OAK_LOG = block(WordsOfRadianceModBlocks.ILLUSION_DARK_OAK_LOG);
	public static final DeferredItem<Item> ILLUSION_SPRUCE_LOG = block(WordsOfRadianceModBlocks.ILLUSION_SPRUCE_LOG);
	public static final DeferredItem<Item> ILLUSION_COBBLESTONE = block(WordsOfRadianceModBlocks.ILLUSION_COBBLESTONE);
	public static final DeferredItem<Item> INK_SPREN_SPAWN_EGG = register("ink_spren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.INK_SPREN.get(), properties));
	public static final DeferredItem<Item> TENSION_WOODEN_PICK = register("tension_wooden_pick", TensionWoodenPickItem::new);
	public static final DeferredItem<Item> TENSION_STONE_PICK = register("tension_stone_pick", TensionStonePickItem::new);
	public static final DeferredItem<Item> TENSION_IRON_PICK = register("tension_iron_pick", TensionIronPickItem::new);
	public static final DeferredItem<Item> TENSION_GOLD_PICK = register("tension_gold_pick", TensionGoldPickItem::new);
	public static final DeferredItem<Item> TENSION_DIAMOND_PICK = register("tension_diamond_pick", TensionDiamondPickItem::new);
	public static final DeferredItem<Item> TENSION_WOODEN_AXE = register("tension_wooden_axe", TensionWoodenAxeItem::new);
	public static final DeferredItem<Item> TENSION_STONE_AXE = register("tension_stone_axe", TensionStoneAxeItem::new);
	public static final DeferredItem<Item> TENSION_IRON_AXE = register("tension_iron_axe", TensionIronAxeItem::new);
	public static final DeferredItem<Item> TENSION_GOLD_AXE = register("tension_gold_axe", TensionGoldAxeItem::new);
	public static final DeferredItem<Item> TENSION_DIAMOND_AXE = register("tension_diamond_axe", TensionDiamondAxeItem::new);
	public static final DeferredItem<Item> TENSION_WOODEN_SHOVEL = register("tension_wooden_shovel", TensionWoodenShovelItem::new);
	public static final DeferredItem<Item> TENSION_STONE_SHOVEL = register("tension_stone_shovel", TensionStoneShovelItem::new);
	public static final DeferredItem<Item> TENSION_IRON_SHOVEL = register("tension_iron_shovel", TensionIronShovelItem::new);
	public static final DeferredItem<Item> TENSION_GOLD_SHOVEL = register("tension_gold_shovel", TensionGoldShovelItem::new);
	public static final DeferredItem<Item> TENSION_DIAMOND_SHOVEL = register("tension_diamond_shovel", TensionDiamondShovelItem::new);
	public static final DeferredItem<Item> TENSION_WOODEN_HOE = register("tension_wooden_hoe", TensionWoodenHoeItem::new);
	public static final DeferredItem<Item> TENSION_STONE_HOE = register("tension_stone_hoe", TensionStoneHoeItem::new);
	public static final DeferredItem<Item> TENSION_IRON_HOE = register("tension_iron_hoe", TensionIronHoeItem::new);
	public static final DeferredItem<Item> TENSION_GOLD_HOE = register("tension_gold_hoe", TensionGoldHoeItem::new);
	public static final DeferredItem<Item> TENSION_DIAMOND_HOE = register("tension_diamond_hoe", TensionDiamondHoeItem::new);
	public static final DeferredItem<Item> TENSION_WOODEN_SWORD = register("tension_wooden_sword", TensionWoodenSwordItem::new);
	public static final DeferredItem<Item> TENSION_STONE_SWORD = register("tension_stone_sword", TensionStoneSwordItem::new);
	public static final DeferredItem<Item> TENSION_IRON_SWORD = register("tension_iron_sword", TensionIronSwordItem::new);
	public static final DeferredItem<Item> TENSION_GOLD_SWORD = register("tension_gold_sword", TensionGoldSwordItem::new);
	public static final DeferredItem<Item> TENSION_DIAMOND_SWORD = register("tension_diamond_sword", TensionDiamondSwordItem::new);
	public static final DeferredItem<Item> TENSION_INFUSED_CHAINMAIL_ARMOR_HELMET = register("tension_infused_chainmail_armor_helmet", TensionInfusedChainmailArmorItem.Helmet::new);
	public static final DeferredItem<Item> TENSION_INFUSED_CHAINMAIL_ARMOR_CHESTPLATE = register("tension_infused_chainmail_armor_chestplate", TensionInfusedChainmailArmorItem.Chestplate::new);
	public static final DeferredItem<Item> TENSION_INFUSED_CHAINMAIL_ARMOR_LEGGINGS = register("tension_infused_chainmail_armor_leggings", TensionInfusedChainmailArmorItem.Leggings::new);
	public static final DeferredItem<Item> TENSION_INFUSED_CHAINMAIL_ARMOR_BOOTS = register("tension_infused_chainmail_armor_boots", TensionInfusedChainmailArmorItem.Boots::new);
	public static final DeferredItem<Item> TENSION_INFUSED_IRON_ARMOR_HELMET = register("tension_infused_iron_armor_helmet", TensionInfusedIronArmorItem.Helmet::new);
	public static final DeferredItem<Item> TENSION_INFUSED_IRON_ARMOR_CHESTPLATE = register("tension_infused_iron_armor_chestplate", TensionInfusedIronArmorItem.Chestplate::new);
	public static final DeferredItem<Item> TENSION_INFUSED_IRON_ARMOR_LEGGINGS = register("tension_infused_iron_armor_leggings", TensionInfusedIronArmorItem.Leggings::new);
	public static final DeferredItem<Item> TENSION_INFUSED_IRON_ARMOR_BOOTS = register("tension_infused_iron_armor_boots", TensionInfusedIronArmorItem.Boots::new);
	public static final DeferredItem<Item> TENSION_INFUSED_GOLD_ARMOR_HELMET = register("tension_infused_gold_armor_helmet", TensionInfusedGoldArmorItem.Helmet::new);
	public static final DeferredItem<Item> TENSION_INFUSED_GOLD_ARMOR_CHESTPLATE = register("tension_infused_gold_armor_chestplate", TensionInfusedGoldArmorItem.Chestplate::new);
	public static final DeferredItem<Item> TENSION_INFUSED_GOLD_ARMOR_LEGGINGS = register("tension_infused_gold_armor_leggings", TensionInfusedGoldArmorItem.Leggings::new);
	public static final DeferredItem<Item> TENSION_INFUSED_GOLD_ARMOR_BOOTS = register("tension_infused_gold_armor_boots", TensionInfusedGoldArmorItem.Boots::new);
	public static final DeferredItem<Item> TENSION_INFUSED_DIAMOND_ARMOR_HELMET = register("tension_infused_diamond_armor_helmet", TensionInfusedDiamondArmorItem.Helmet::new);
	public static final DeferredItem<Item> TENSION_INFUSED_DIAMOND_ARMOR_CHESTPLATE = register("tension_infused_diamond_armor_chestplate", TensionInfusedDiamondArmorItem.Chestplate::new);
	public static final DeferredItem<Item> TENSION_INFUSED_DIAMOND_ARMOR_LEGGINGS = register("tension_infused_diamond_armor_leggings", TensionInfusedDiamondArmorItem.Leggings::new);
	public static final DeferredItem<Item> TENSION_INFUSED_DIAMOND_ARMOR_BOOTS = register("tension_infused_diamond_armor_boots", TensionInfusedDiamondArmorItem.Boots::new);
	public static final DeferredItem<Item> ADHESIVE = block(WordsOfRadianceModBlocks.ADHESIVE);
	public static final DeferredItem<Item> CRYPTIC_SPAWN_EGG = register("cryptic_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.CRYPTIC.get(), properties));
	public static final DeferredItem<Item> HONOURSPREN_SPAWN_EGG = register("honourspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.HONOURSPREN.get(), properties));
	public static final DeferredItem<Item> HIGHSPREN_SPAWN_EGG = register("highspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.HIGHSPREN.get(), properties));
	public static final DeferredItem<Item> ASHSPREN_SPAWN_EGG = register("ashspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.ASHSPREN.get(), properties));
	public static final DeferredItem<Item> CULTIVATIONSPREN_SPAWN_EGG = register("cultivationspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.CULTIVATIONSPREN.get(), properties));
	public static final DeferredItem<Item> MISTSPREN_SPAWN_EGG = register("mistspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.MISTSPREN.get(), properties));
	public static final DeferredItem<Item> LIGHTSPREN_SPAWN_EGG = register("lightspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.LIGHTSPREN.get(), properties));
	public static final DeferredItem<Item> PEAKSPREN_SPAWN_EGG = register("peakspren_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.PEAKSPREN.get(), properties));
	public static final DeferredItem<Item> WILLSHAPER_BLADE = register("willshaper_blade", WillshaperBladeItem::new);
	public static final DeferredItem<Item> WINDRUNNER_BLADE = register("windrunner_blade", WindrunnerBladeItem::new);
	public static final DeferredItem<Item> SKYBREAKER_BLADE = register("skybreaker_blade", SkybreakerBladeItem::new);
	public static final DeferredItem<Item> DUSTBRINGER_BLADE = register("dustbringer_blade", DustbringerBladeItem::new);
	public static final DeferredItem<Item> EDGEDANCER_BLADE = register("edgedancer_blade", EdgedancerBladeItem::new);
	public static final DeferredItem<Item> TRUTHWATCHER_BLADE = register("truthwatcher_blade", TruthwatcherBladeItem::new);
	public static final DeferredItem<Item> LIGHTWEAVER_BLADE = register("lightweaver_blade", LightweaverBladeItem::new);
	public static final DeferredItem<Item> ELSECALLER_BLADE = register("elsecaller_blade", ElsecallerBladeItem::new);
	public static final DeferredItem<Item> STONEWARD_BLADE = register("stoneward_blade", StonewardBladeItem::new);
	public static final DeferredItem<Item> INFUSED_STONES = block(WordsOfRadianceModBlocks.INFUSED_STONES);
	public static final DeferredItem<Item> WINDRUNNER_SHARDPLATE_HELMET = register("windrunner_shardplate_helmet", WindrunnerShardplateItem.Helmet::new);
	public static final DeferredItem<Item> WINDRUNNER_SHARDPLATE_CHESTPLATE = register("windrunner_shardplate_chestplate", WindrunnerShardplateItem.Chestplate::new);
	public static final DeferredItem<Item> WINDRUNNER_SHARDPLATE_LEGGINGS = register("windrunner_shardplate_leggings", WindrunnerShardplateItem.Leggings::new);
	public static final DeferredItem<Item> WINDRUNNER_SHARDPLATE_BOOTS = register("windrunner_shardplate_boots", WindrunnerShardplateItem.Boots::new);
	public static final DeferredItem<Item> SKYBREAKER_PLATE_HELMET = register("skybreaker_plate_helmet", SkybreakerPlateItem.Helmet::new);
	public static final DeferredItem<Item> SKYBREAKER_PLATE_CHESTPLATE = register("skybreaker_plate_chestplate", SkybreakerPlateItem.Chestplate::new);
	public static final DeferredItem<Item> SKYBREAKER_PLATE_LEGGINGS = register("skybreaker_plate_leggings", SkybreakerPlateItem.Leggings::new);
	public static final DeferredItem<Item> SKYBREAKER_PLATE_BOOTS = register("skybreaker_plate_boots", SkybreakerPlateItem.Boots::new);
	public static final DeferredItem<Item> DUSTBRINGER_PLATE_HELMET = register("dustbringer_plate_helmet", DustbringerPlateItem.Helmet::new);
	public static final DeferredItem<Item> DUSTBRINGER_PLATE_CHESTPLATE = register("dustbringer_plate_chestplate", DustbringerPlateItem.Chestplate::new);
	public static final DeferredItem<Item> DUSTBRINGER_PLATE_LEGGINGS = register("dustbringer_plate_leggings", DustbringerPlateItem.Leggings::new);
	public static final DeferredItem<Item> DUSTBRINGER_PLATE_BOOTS = register("dustbringer_plate_boots", DustbringerPlateItem.Boots::new);
	public static final DeferredItem<Item> EDGEDANCER_PLATE_HELMET = register("edgedancer_plate_helmet", EdgedancerPlateItem.Helmet::new);
	public static final DeferredItem<Item> EDGEDANCER_PLATE_CHESTPLATE = register("edgedancer_plate_chestplate", EdgedancerPlateItem.Chestplate::new);
	public static final DeferredItem<Item> EDGEDANCER_PLATE_LEGGINGS = register("edgedancer_plate_leggings", EdgedancerPlateItem.Leggings::new);
	public static final DeferredItem<Item> EDGEDANCER_PLATE_BOOTS = register("edgedancer_plate_boots", EdgedancerPlateItem.Boots::new);
	public static final DeferredItem<Item> TRUTHWATCHER_PLATE_HELMET = register("truthwatcher_plate_helmet", TruthwatcherPlateItem.Helmet::new);
	public static final DeferredItem<Item> TRUTHWATCHER_PLATE_CHESTPLATE = register("truthwatcher_plate_chestplate", TruthwatcherPlateItem.Chestplate::new);
	public static final DeferredItem<Item> TRUTHWATCHER_PLATE_LEGGINGS = register("truthwatcher_plate_leggings", TruthwatcherPlateItem.Leggings::new);
	public static final DeferredItem<Item> TRUTHWATCHER_PLATE_BOOTS = register("truthwatcher_plate_boots", TruthwatcherPlateItem.Boots::new);
	public static final DeferredItem<Item> LIGHTWEAVER_PLATE_HELMET = register("lightweaver_plate_helmet", LightweaverPlateItem.Helmet::new);
	public static final DeferredItem<Item> LIGHTWEAVER_PLATE_CHESTPLATE = register("lightweaver_plate_chestplate", LightweaverPlateItem.Chestplate::new);
	public static final DeferredItem<Item> LIGHTWEAVER_PLATE_LEGGINGS = register("lightweaver_plate_leggings", LightweaverPlateItem.Leggings::new);
	public static final DeferredItem<Item> LIGHTWEAVER_PLATE_BOOTS = register("lightweaver_plate_boots", LightweaverPlateItem.Boots::new);
	public static final DeferredItem<Item> ELSECALLER_PLATE_HELMET = register("elsecaller_plate_helmet", ElsecallerPlateItem.Helmet::new);
	public static final DeferredItem<Item> ELSECALLER_PLATE_CHESTPLATE = register("elsecaller_plate_chestplate", ElsecallerPlateItem.Chestplate::new);
	public static final DeferredItem<Item> ELSECALLER_PLATE_LEGGINGS = register("elsecaller_plate_leggings", ElsecallerPlateItem.Leggings::new);
	public static final DeferredItem<Item> ELSECALLER_PLATE_BOOTS = register("elsecaller_plate_boots", ElsecallerPlateItem.Boots::new);
	public static final DeferredItem<Item> WILLSHAPER_PLATE_HELMET = register("willshaper_plate_helmet", WillshaperPlateItem.Helmet::new);
	public static final DeferredItem<Item> WILLSHAPER_PLATE_CHESTPLATE = register("willshaper_plate_chestplate", WillshaperPlateItem.Chestplate::new);
	public static final DeferredItem<Item> WILLSHAPER_PLATE_LEGGINGS = register("willshaper_plate_leggings", WillshaperPlateItem.Leggings::new);
	public static final DeferredItem<Item> WILLSHAPER_PLATE_BOOTS = register("willshaper_plate_boots", WillshaperPlateItem.Boots::new);
	public static final DeferredItem<Item> STONEWARD_PLATE_HELMET = register("stoneward_plate_helmet", StonewardPlateItem.Helmet::new);
	public static final DeferredItem<Item> STONEWARD_PLATE_CHESTPLATE = register("stoneward_plate_chestplate", StonewardPlateItem.Chestplate::new);
	public static final DeferredItem<Item> STONEWARD_PLATE_LEGGINGS = register("stoneward_plate_leggings", StonewardPlateItem.Leggings::new);
	public static final DeferredItem<Item> STONEWARD_PLATE_BOOTS = register("stoneward_plate_boots", StonewardPlateItem.Boots::new);
	public static final DeferredItem<Item> BEADS_BUCKET = register("beads_bucket", BeadsItem::new);
	public static final DeferredItem<Item> HONOURSPREN_SHADESMAR_SPAWN_EGG = register("honourspren_shadesmar_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.HONOURSPREN_SHADESMAR.get(), properties));
	public static final DeferredItem<Item> CRYPTIC_SHADESMAR_SPAWN_EGG = register("cryptic_shadesmar_spawn_egg", properties -> new SpawnEggItem(WordsOfRadianceModEntities.CRYPTIC_SHADESMAR.get(), properties));
	public static final DeferredItem<Item> OATHGATE_STONE = block(WordsOfRadianceModBlocks.OATHGATE_STONE);
	public static final DeferredItem<Item> KALAKS_BLADE = register("kalaks_blade", KalaksBladeItem::new);
	public static final DeferredItem<Item> JEZRIENS_BLADE = register("jezriens_blade", JezriensBladeItem::new);
	public static final DeferredItem<Item> NALES_BLADE = register("nales_blade", NalesBladeItem::new);
	public static final DeferredItem<Item> CHANNAHS_BLADE = register("channahs_blade", ChannahsBladeItem::new);
	public static final DeferredItem<Item> VEDELS_BLADE = register("vedels_blade", VedelsBladeItem::new);
	public static final DeferredItem<Item> PRALLAS_BLADE = register("prallas_blade", PrallasBladeItem::new);
	public static final DeferredItem<Item> ASHS_BLADE = register("ashs_blade", AshsBladeItem::new);
	public static final DeferredItem<Item> BATTARS_BLADE = register("battars_blade", BattarsBladeItem::new);
	public static final DeferredItem<Item> TALNS_BLADE = register("talns_blade", TalnsBladeItem::new);
	public static final DeferredItem<Item> JEZRIENS_BLADE_BONDED = register("jezriens_blade_bonded", JezriensBladeBondedItem::new);
	public static final DeferredItem<Item> NALES_BLADE_BONDED = register("nales_blade_bonded", NalesBladeBondedItem::new);
	public static final DeferredItem<Item> CHANNAHS_BLADE_BONDED = register("channahs_blade_bonded", ChannahsBladeBondedItem::new);
	public static final DeferredItem<Item> VEDELS_BLADE_BONDED = register("vedels_blade_bonded", VedelsBladeBondedItem::new);
	public static final DeferredItem<Item> PRALLAS_BLADE_BONDED = register("prallas_blade_bonded", PrallasBladeBondedItem::new);
	public static final DeferredItem<Item> ASHS_BLADE_BONDED = register("ashs_blade_bonded", AshsBladeBondedItem::new);
	public static final DeferredItem<Item> BATTARS_BLADE_BONDED = register("battars_blade_bonded", BattarsBladeBondedItem::new);
	public static final DeferredItem<Item> TALNS_BLADE_BONDED = register("talns_blade_bonded", TalnsBladeBondedItem::new);
	public static final DeferredItem<Item> KALAKS_BLADE_BONDED = register("kalaks_blade_bonded", KalaksBladeBondedItem::new);
	public static final DeferredItem<Item> DEAD_BLUE_BLADE = register("dead_blue_blade", DeadBlueBladeItem::new);
	public static final DeferredItem<Item> DEAD_BLACK_BLADE = register("dead_black_blade", DeadBlackBladeItem::new);
	public static final DeferredItem<Item> DEAD_RED_BLADE = register("dead_red_blade", DeadRedBladeItem::new);
	public static final DeferredItem<Item> DEAD_WHITE_BLADE = register("dead_white_blade", DeadWhiteBladeItem::new);
	public static final DeferredItem<Item> DEAD_GREEN_BLADE = register("dead_green_blade", DeadGreenBladeItem::new);
	public static final DeferredItem<Item> DEAD_PINK_RED_BLADE = register("dead_pink_red_blade", DeadPinkRedBladeItem::new);
	public static final DeferredItem<Item> DEAD_ZIRCON_BLADE = register("dead_zircon_blade", DeadZirconBladeItem::new);
	public static final DeferredItem<Item> DEAD_PURPLE_BLADE = register("dead_purple_blade", DeadPurpleBladeItem::new);
	public static final DeferredItem<Item> DEAD_ORANGE_BLADE = register("dead_orange_blade", DeadOrangeBladeItem::new);
	public static final DeferredItem<Item> DEAD_BLUE_BLADE_WITH_GEM = register("dead_blue_blade_with_gem", DeadBlueBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_BLACK_BLADE_WITH_GEM = register("dead_black_blade_with_gem", DeadBlackBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_RED_BLADE_WITH_GEM = register("dead_red_blade_with_gem", DeadRedBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_WHITE_BLADE_WITH_GEM = register("dead_white_blade_with_gem", DeadWhiteBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_GREEN_BLADE_WITH_GEM = register("dead_green_blade_with_gem", DeadGreenBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_PINK_RED_BLADE_WITH_GEM = register("dead_pink_red_blade_with_gem", DeadPinkRedBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_ZIRCON_BLADE_WITH_GEM = register("dead_zircon_blade_with_gem", DeadZirconBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_PURPLE_BLADE_WITH_GEM = register("dead_purple_blade_with_gem", DeadPurpleBladeWithGemItem::new);
	public static final DeferredItem<Item> DEAD_STONEWARD_BLADE_WITH_GEM = register("dead_stoneward_blade_with_gem", DeadStonewardBladeWithGemItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLUE_BLADE = register("bonded_dead_blue_blade", BondedDeadBlueBladeItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_BLACK = register("bonded_dead_blade_black", BondedDeadBladeBlackItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_RED = register("bonded_dead_blade_red", BondedDeadBladeRedItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_WHITE = register("bonded_dead_blade_white", BondedDeadBladeWhiteItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_GREEN = register("bonded_dead_blade_green", BondedDeadBladeGreenItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_PINK_RED = register("bonded_dead_blade_pink_red", BondedDeadBladePinkRedItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_ZIRCON = register("bonded_dead_blade_zircon", BondedDeadBladeZirconItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_PURPLE = register("bonded_dead_blade_purple", BondedDeadBladePurpleItem::new);
	public static final DeferredItem<Item> BONDED_DEAD_BLADE_ORANGE = register("bonded_dead_blade_orange", BondedDeadBladeOrangeItem::new);
	public static final DeferredItem<Item> STONE_BLADE_JES = block(WordsOfRadianceModBlocks.STONE_BLADE_JES);
	public static final DeferredItem<Item> STONE_BLADE_NAL = block(WordsOfRadianceModBlocks.STONE_BLADE_NAL);
	public static final DeferredItem<Item> STONE_BLADE_CHAN = block(WordsOfRadianceModBlocks.STONE_BLADE_CHAN);
	public static final DeferredItem<Item> STONE_BLADE_VED = block(WordsOfRadianceModBlocks.STONE_BLADE_VED);
	public static final DeferredItem<Item> STONE_BLADE_PAI = block(WordsOfRadianceModBlocks.STONE_BLADE_PAI);
	public static final DeferredItem<Item> STONE_BLADE_ASH = block(WordsOfRadianceModBlocks.STONE_BLADE_ASH);
	public static final DeferredItem<Item> STONE_BLADE_BAT = block(WordsOfRadianceModBlocks.STONE_BLADE_BAT);
	public static final DeferredItem<Item> STONE_BLADE_KAL = block(WordsOfRadianceModBlocks.STONE_BLADE_KAL);
	public static final DeferredItem<Item> STONE_BLADE_TALN = block(WordsOfRadianceModBlocks.STONE_BLADE_TALN);

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.registerItem(block.getId().getPath(), properties -> new BlockItem(block.get(), properties), new Item.Properties());
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new DedicationLandBookInventoryCapability(stack), DEDICATION_LAND_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new DedicationConquestBookInventoryCapability(stack), DEDICATION_CONQUEST_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new DedicationOccupationBookInventoryCapability(stack), DEDICATION_OCCUPATION_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new DedicationBeyondDeathBookInventoryCapability(stack), DEDICATION_BEYOND_DEATH_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new CrusadeTyrantBookInventoryCapability(stack), CRUSADE_TYRANT_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new CrusadeMonstrosityBookInventoryCapability(stack), CRUSADE_MONSTROSITY_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new DefendInnocentCrusadeBookInventoryCapability(stack), DEFEND_INNOCENT_CRUSADE_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new RestoreOrderCrusadeBookInventoryCapability(stack), RESTORE_ORDER_CRUSADE_BOOK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new HuntCrusadeBookInventoryCapability(stack), HUNT_CRUSADE_BOOK.get());
	}
}
